### ISSUE TITLE
@Import is broken?

### ISSUE THREAD

**Issue by Mystagogue** [twbs/bootstrap-sass#1009]
I'm using Windows 10.  Installation was successful with 'npm install bootstrap-sass', but when I try to @import 'bootstrap', I'm told that it cannot be found.

>Module build failed: Error: C:\repos\vso\AxisCodeWeb\src\components\App\App.scss:16:1: Failed to find 'bootstrap'

I tried changing to @import 'bootstrap-sass', and this also does not work.  

>Module build failed: Error: C:\repos\vso\AxisCodeWeb\src\components\App\App.scss:16:1: Failed to find 'bootstrap-sass'

I can make slight progress by trying 'npm install bootstrap' and using @import 'bootstrap', but that is not a dependency of bootstrap-sass and it means I am no longer using bootstrap-sass.  

The context of my problem is that I'm trying to [incorporate bootstrap into the react-starter-kit](https://github.com/kriasoft/react-starter-kit/issues/179).  In that discussion they don't bother with bootstrap-sass, which makes no sense to me.  The react starter kit uses SASS, and so bootstrap-sass seems like the right choice.

**Comment by iammikecohen** [comment]
The reason you can't import Bootstrap after installing it with NPM is because Sass doesn't know that module exists. You need to either import Bootstrap using a relative path to your node_modules folder (bad) or use (Eyeglass)[https://github.com/sass-eyeglass/eyeglass] to give Sass the ability to use Bootstrap as a node module. Eyeglass is not yet supported by Bootstrap. You can look at my pull request to see how I have added Eyeglass support and how you can import parts or all of Bootstrap in a Sass project that uses Eyeglass.

**Comment by frob** [comment]
Why is using a relative path bad?

**Comment by iammikecohen** [comment]
It's not the worst thing but if you have other developers working on your project and they don't have their node_modules folder in the same location as you or they have changed the name of that folder then your @import rule will break. It seems more future proof to have a way to @import by the library name without coupling that declaration to a given dependency manager.

**Comment by frob** [comment]
I was under the impression that node_modules cannot be moved or renamed. I
could see there possibly being an issue if someone had something globally
installed, but even then running npm install should take care of that.

**Comment by cvrebert** [comment]
Unless this is Eyeglass-related, this sounds like a problem with your environment/path setup rather than a bug in bootstrap-sass. Please use StackOverflow for those sorts of troubleshooting questions. Good luck!
