### ISSUE TITLE
yarn install not working

### ISSUE THREAD

**Issue by jontelm** [twbs/bootstrap-sass#1097]
When trying to install with yarn instead of npm the folder is missing the assets folder.

````
yarn install
````

yarn version: 16

Works for me now with yarn 18.1 and a good connection.

**Comment by maiis** [comment]
@jontelm How did you fixed it ?

**Comment by kesor** [comment]
Why was this closed? It still keeps happening, would help to have an explanation.

**Comment by jontelm** [comment]
@kesor I thought my problem was my connection so I closed it.

**Comment by maiis** [comment]
When I had this issue... turns out I had a .yarnignore file, that was ignoring the assets folder 🤦‍♂️

**Comment by jimmytheneutrino** [comment]
It seems to be called .yarnclean now (https://yarnpkg.com/en/docs/cli/clean), and yes, it includes assets by default.

Docs say that "yarn clean" is "an advanced command" and should be used with care. I agree but this is such a common name for cleaning artifacts after some build (e.g. similar to gradle clean or mvn clean) that most people try to invoke it and might end up with a non-functioning project because of a hard-to-detect bug.

IMHO it is better to change the name or to print out a big colorful WARNING when "yarn clean" is invoked.

**Comment by t47io** [comment]
yup, should not`clean` the `assets` dir.
