### ISSUE TITLE
@import 'Bootstrap' not working

### ISSUE THREAD

**Issue by calcazar** [twbs/bootstrap-sass#1119]
Should we update the documentation to reflect that the way of getting this to work is:

$bootstrap-sass-asset-helper: true;
@import "~bootstrap-sass/assets/stylesheets/bootstrap";

and not

@import "bootstrap"

Some explanation on why @import "bootstrap" doesn't work would be appreciated as well for my sanity :)

**Comment by thomas-mcdonald** [comment]
Looks like Webpack resolution syntax? `@import bootstrap` won't work there since that's not how Webpack works.

I haven't used Bootstrap with Webpack so unable to comment on the 'best' way to do it, but your working example looks correct from my experiences with other frameworks.

**Comment by Johann-S** [comment]
We will add an "How-to" use Bootstrap with Webpack on Bootstrap main repository, maybe this PR can help you : https://github.com/twbs/bootstrap/pull/22423

**Comment by dalu** [comment]
eh, well sorry but I'm completely lost.
I installed 'bootstrap-sass' via bower, because that's the simplest way.
However the import doesn't work when using the ruby sass compiler.
```
/home/darko/.gem/ruby/2.2.0/bin/sass app.scss:app.css
Error: File to import not found or unreadable: bootstrap.
        on line 1 of app.scss
  Use --trace for backtrace.

Process finished with exit code 65
```
The front end is moving so fast with grunt,gulp, now webpack idk what's next, there's so much and I'm used to bower or just npm.
Why doesn't `@import 'bootstrap'` work?

The other project I used was zurb foundation, version 3 a few years back.
The sass file/s also had `@import 'foundation'` well how does sass know where it's installed?
Should I just give the absolute path?
Can I configure a default prefix path like ./bower-components/

**Comment by clottman** [comment]
If you're calling `@import 'bootstrap'` from another Sass file, you need to give it a path hint if it's bootstrap and your file aren't in the same directory. If you have something like 

```
Assets/
  _bootstrap.scss
  MyFiles/
      my_styles.scss
```

`my_styles.scss` would use `@import "..\bootstrap"`. If you include bootstrap in this way, then you only have to serve my_styles.css to the browser - bootstrap is included in that file now. 

`@import` in Sass is different than in Webpack - it can be confusing, but remember that all the `@import`s in a compiled scss file will be resolved and removed by the Sass compiler, and won't ever reach the browser. [Here's](http://vanseodesign.com/css/sass-the-import-directive/) a good resource on using @import in Sass.
