### ISSUE TITLE
@function theme-color function missing

### ISSUE THREAD

**Issue by niumalta** [twbs/bootstrap-sass#1142]
Is there a reason why the _functions.scss is missing? We have an Issue where another package is calling the theme-color function but unfortunately it cannot be found in bootstrap-sass package.

**Comment by justinxreese** [comment]
I ended up asking the same question because I missed the line at the top of the repo

> This is Bootstrap 3. For Bootstrap 4 use the [Bootstrap Ruby](https://github.com/twbs/bootstrap-rubygem) gem if you use Ruby, and the [main repo](https://github.com/twbs/bootstrap) otherwise.

As far as I can tell, if you're using something that is relying on or complaining about _functions.scss not being defined then you probably are using something that wants Bootstrap 4 and should not be using `bootstrap-sass`.

Hope this helps someone in the future ⌛️
