### ISSUE TITLE
replace sass with sassc

### ISSUE THREAD

**Issue by dennisvandehoef** [twbs/bootstrap-sass#1156]
Replace the usage of the sass gem with the sassc gem, as suggested in the end-of-life blog post: http://sass.logdown.com/posts/7081811

According to this benchmark, it also might speed up the sass compilation time as an extra win: https://marianposaceanu.com/articles/making-rails-asset-pipeline-faster

**Comment by mokolabs** [comment]
FWIW, I don't think adding sassc support will be that difficult -- at least on the 2.X branch.

My app is stuck on Bootstrap 2.3, but I wanted sassc support... so I cloned the current gem, rolled back to the original 2.3 release commit (since there is no tracking branch for 2.3), and then added sassc.

You can see it here:
https://github.com/mokolabs/bootstrap-sass-2.3-with-sassc-rails

**Comment by mileslane** [comment]
What is the status of this?

**Comment by mokolabs** [comment]
Sweet. Thanks, @glebm!
