### ISSUE TITLE
Bootstrap 3 missing .form-inline .form-group {display:inline-block;} part

### ISSUE THREAD

**Issue by iamsolankiamit** [twbs/bootstrap-sass#413]
The css doesn't consist this portion .form-inline .form-group {display:inline-block;}. how do i add it, its is there in original bootstrap source.

**Comment by Hugoer** [comment]
Hi, I'm using 'Bootstrap-sass' and I just want the grid and some other more characteristic.

I'm adding:

import "vendor / bootstrap-sass / variables";
import "vendor / bootstrap-sass / mixins";
import "vendor / bootstrap-sass / normalize";
import "vendor / bootstrap-sass / scaffolding";
import "vendor / bootstrap-sass / grid";
import "vendor / bootstrap-sass / responsive-utilities";
import "vendor / bootstrap-sass / modals";
import "vendor / bootstrap-sass / dropdowns";
import "vendor / bootstrap-sass / navs";
import "vendor / bootstrap-sass / navbar";

But it is forcing me to add:

import "vendor / bootstrap-sass / forms";

If I do not add that .scss not compiled by the css is missing:

"Error: not mixin named form-inline".

The problem is that the file "_forms.scss" applies more styles of necessary (for me). It would be necessary to move the mixin "mixin form-inline" to "Mixins" folder?
