### ISSUE TITLE
"Placeholder-only" version of _bootstrap.scss

### ISSUE THREAD

**Issue by tuespetre** [twbs/bootstrap-sass#741]
It would be nice if you built the `.scss` file hierarchy to have all of the top-level declarations (`.container`, `.navbar`, `.navbar-inverse`, etc.) be declared as *placeholders*. You could then have mirror files that declare the concrete classes that extend from the placeholders and offer two 'main' files: one that people can import for just the variables/mixins/placeholders, and another one people can import to have all of the concrete classes.

For an example use case, I am developing a header that will be shared across a network of internal web applications and I want to only include the css necessary for styling the component, not all of the 'default' bootstrap styles.

**Comment by madeofpeople** [comment]
If the grid mixins alone were converted to placeholders file sizes would be considerably reduced.

**Comment by tuespetre** [comment]
Still interested in this but I understand bootstrap 4 is well underway now? How would that development effort factor in to this feature request?

**Comment by fntneves** [comment]
+1 Need this, really.

**Comment by glebm** [comment]
Not doing this in v3, but considering for v4.

**Comment by glebm** [comment]
We are considering this for v4.

**Comment by coltonbrugger** [comment]
+1 Glad to see this issue was brought up. Sad it seems to have died though.

**Comment by glebm** [comment]
I proposed the feature, and there was no strong disagreement about it apart from https://github.com/mdo/css-output. Unfortunately, I did not have time to implement it. You can try bringing it up again on the upstream tracker.

**Comment by kalaomer** [comment]
Check this out: https://github.com/kalaomer/griflex

This repo is uptade of grid system which is used in bootstrap v4 beta for placeholder.

We use this repo for our business.

**Comment by Bartmax** [comment]
why not just define them as:
```
%btn,
.btn {
    // stuff here
}
```
no need for placeholder file (?)

**Comment by david-treblig** [comment]
+1. I don't know if the fact that it was added to the v4 milestone and then closed means that it was considered properly, but a quick look into Griflex and the way that they do it is quite interesting. 

https://github.com/kalaomer/griflex/blob/master/scss/griflex/_grid.scss

They have a variable that enables the container classes to be outputted in the main CSS, otherwise, they are only place holder selectors. That would be interesting and possibly just by reversing the logic : always include the classes, but allow people to remove them.

**Comment by csscoderRU** [comment]
I re-wrote Bootstrap v4 grid system for my needs. Can it be useful to someone else [Bootstrap Silent Grid](https://github.com/csscoderRU/bootstrap-silent-grid)

**Comment by CarlangasGO** [comment]
+1 I don't understand why they don't implement it

**Comment by sogk** [comment]
+1 After having searched for Sass implementations of Bootstrap 4 + WooCommerce, I have come a cross some seriously bad implementations where the compiled style sheet is > 2MB. This, because of extensive use of @extend which we all know should be avoided (see: [https://webinista.com/updates/dont-use-extend-sass/]).

This would be avoided by implementing sass placeholders on core features.
