### ISSUE TITLE
pointer-events: none on .form-control-feedback kills tooltips

### ISSUE THREAD

**Issue by justin-hackin** [twbs/bootstrap-sass#798]
Commenting out pointer-events: none (_forms.scss:346) makes the tooltips work again.  Not sure if this is a result of complex interaction of styles in my theme, may need confirmation/isolation.  It was a result of updating the bootstrap scss files to support form-control-feedback in this theme : http://wrapbootstrap.com/preview/WB0135486

**Comment by cvrebert** [comment]
A. CSS bugs not related to the Sass translation process should be reported upstream (https://github.com/twbs/bootstrap) instead of here.
B. Assuming you're referring to putting a tooltip on the form-control-feedback's Glyphicon, the `pointer-events: none` is intentional so that the Glyphicon itself isn't selectable/clickable.
