### ISSUE TITLE
Font flickers on carousel slide

### ISSUE THREAD

**Issue by kozhin** [twbs/bootstrap-sass#815]
Hi,
I noticed that in the latest Safari browser all fonts flicker when bootstrap3 carousel moves a slide. This affects only texts under the carousel.
To fix this problem I've added the following to my project:
```
.carousel-inner {
        -webkit-backface-visibility: hidden;
        -webkit-perspective: 1000;
}
```
I'm not sure if this is related directly to bootstrap-sass project. Can anyone clarify and apply the fix?

**Comment by cvrebert** [comment]
Bootstrap already applies such styles to the individual carousel items, although not the carousel-inner itself; see https://github.com/twbs/bootstrap/blob/15c9c3aef7f047c9cce45fd33ada799e99fbd390/less/carousel.less#L31
Since your suggestion isn't related to the Sass conversion process or packaging, it should be filed upstream (https://github.com/twbs/bootstrap ) instead of here. Thanks!

**Comment by cvrebert** [comment]
Also, you might be encountering http://stackoverflow.com/questions/12502234/how-to-prevent-webkit-text-rendering-change-during-css-transition
