### ISSUE TITLE
Using Bootstrap 3.3.x on Rails 3.2.x

### ISSUE THREAD

**Issue by terenceponce** [twbs/bootstrap-sass#830]
I'm not sure if I understand this correctly, but in the README, it says:

> bootstrap-sass is no longer compatible with Rails 3. The latest version of bootstrap-sass compatible with Rails 3.2 is v3.1.1.0.

As I understand, bootstrap-sass' version reflects the exact Twitter Bootstrap version it says. Does that mean I won't be able to use the newer versions of Twitter Bootstrap (beyond 3.1.1) unless I move to Rails 4?

**Comment by glebm** [comment]
No versions newer than 3.1.1.0 support Rails 3. It is reportedly possible to use backports of the gems that enable Bootstrap compatibility with Rails 3: https://github.com/twbs/bootstrap-sass/issues/806#issuecomment-70167287.

> bootstrap-sass' version reflects the exact Twitter Bootstrap version it says.

[Not since v3.3.3+](https://github.com/twbs/bootstrap-sass/blob/v3.3.3/CHANGELOG.md#333) as we switched to semver.

**Comment by terenceponce** [comment]
Good to know. Thanks for clarifying!
