### ISSUE TITLE
Sourcemaps configuration

### ISSUE THREAD

**Issue by gkatsanos** [twbs/bootstrap-sass#853]
I have a Rails project and I don't see any sourcemap files generated. What  should I do ? I cand find anything useful online.

**Comment by Lelith** [comment]
hi there, i have kind of the same problem. i just tried it the "casual" way described here: http://thesassway.com/intermediate/using-source-maps-with-sass

but if i try to call the command on my application.scss i get an error that i can not find the imported bootstrap source files. which kind of makes sense. because they're hidden inside the gem. so it can not create a map for sources which you do not have. 

so i also do not have a solution for this :(

**Comment by gkatsanos** [comment]
This will be fixed when the new version of SPROCKETS is out towards end of
the year... Check the issue queue of sprockets
