### ISSUE TITLE
unbound variable $form-group-margin-bottom error

### ISSUE THREAD

**Issue by nrsedat** [twbs/bootstrap-sass#876]
sass compile fails after upgrading to 3.3.4 with the following error
unbound variable $form-group-margin-bottom on line 207 in bootstrap-sass/assets/stylesheets/bootstrap/_forms.scss.

**Comment by charlatan154** [comment]
I have this error too.

**Comment by charlatan154** [comment]
Ok i found it's because i'm overwriting _variables.scss for my own project. Merging the new variables into my custom ones fixed the problem.

**Comment by silvenon** [comment]
I thought this was an issue with Bootstrap, but @charlatan154 is right. I forgot that I made a copy of `_variables.scss` from 3.3.3 which is missing the variable.

We should always include both our copy and the original, because original ones will get overwritten and new ones will stay untouched after an update, which is what we want.

**Comment by nrsedat** [comment]
Thank you
