### ISSUE TITLE
Too slow when i change scss file and refresh the browser

### ISSUE THREAD

**Issue by linjunzhu** [twbs/bootstrap-sass#901]
Envrioment:

Rails 4.2
Mac OSX 10.9

gem 'bootstrap-sass', '~> 3.3.4'

add it to my `application.scss`
```ruby
@import "bootstrap-sprockets";
@import "bootstrap";
```

Ok, when i change something from scss file and refresh the browser, it took two seconds at least that can saw result from server.

When i remove 
```ruby
@import "bootstrap-sprockets";
@import "bootstrap";
```
and everything is right ......

**Comment by cvrebert** [comment]
I doubt there's much we can do about this. Ruby Sass is relatively slow (and we can't do anything about that ourselves) and Bootstrap is relatively large (because it offers many widgets/features). Plus, I don't think compilation speed is on our priorities list (at least to the extent that 2secs wouldn't be acceptable).

If you're not using all of Bootstrap, you can remove the `@import`s of the unused widgets from `bootstrap.scss`, which should lower the compilation time.
You could also try using the Ruby bindings for libsass instead of using Ruby Sass, as libsass is much faster, although libsass still has some bugs and hasn't reached full feature parity yet.

/fyi @twbs/sass
