### ISSUE TITLE
Why Bootstrap sass gem lazy loads icon fonts in Rails?

### ISSUE THREAD

**Issue by ciaoben** [twbs/bootstrap-sass#957]
I have noticed that in my app, where I am using the bootstrap-sass gem to integrate bootstrap, it make a request for the font when I need a glyphicon.

Basically, the icon appear few seconds later because it has to retrieve it from the server. How can I avoid this?

I can't find any doc about this.

**Comment by glebm** [comment]
This is the regular behaviour of resources linked from CSS, bootstrap isn't doing anything special here. You can try inlining them as data-uris. Instead of importing `bootstrap-sprockets` and instead use something like:

```sass
@function twbs-font-path($path) {
  @return asset-data-uri($path);
}

@function twbs-image-path($path) {
  @return image-path($path);
}

$bootstrap-sass-asset-helper: true;
```

`asset-data-uri` is [defined](https://github.com/petebrowne/sprockets-sass/blob/master/lib/sprockets/sass/functions.rb#L13) by sprockets-sass.

See my blog post on how inlining might help: http://blog.glebm.com/2013/08/28/inline-css-fonts.html

**Comment by ciaoben** [comment]
I am a stupid you are right, I guess I am noticing it because it not caching anything, no anytime I refresh the page I see this delay.

Thanks

**Comment by glebm** [comment]
The delay (also known as Flash of Unstyled Content) can be quite annoying to the user (esp. on slow networks e.g. mobile), so I tend to inline webfonts and small images in all my websites.
