### ISSUE TITLE
Gruntfile!!!

### ISSUE THREAD

**Issue by T04435** [twbs/bootstrap-sass#962]
Sorry if This is a newby dam question but I cant find the Gruntfile. Can't do use of grunt dist or anything... Any help please

**Comment by MichaelMallett** [comment]
Yeah this documentation and differences between the two is really confusing. Surely the only difference should be swapping less for sass?

**Comment by cvrebert** [comment]
There is no Gruntfile. At the time this project was created, libsass was either nonexistent or not usable, so AFAIK only Ruby folks used this project, because Ruby Sass was the only choice. And thus it has integrations for Rails, etc.
Fortunately, compilation is pretty simple. Just run [`assets/stylesheets/_bootstrap.scss`](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/_bootstrap.scss) through your Sass compiler (or `@import` it from your own Sass file) and then run the output through Autoprefixer.

**Comment by m10n** [comment]
I'd really like to be able to use Grunt, particularly in preparation for [v4 Sass](http://v4-alpha.getbootstrap.com/getting-started/build-tools/#tooling-setup). I tried to switch from Less this weekend thinking it'd be as straightforward (the [docs intro](http://getbootstrap.com/getting-started/#download) actually makes a Sass install sound easier than Less) but was a bit blindsided that `gruntfile.js` wasn't included.

@cvrebert Since you could probably do this in your sleep, do you (or someone else reading this) have a starter executable Gruntfile.js handy? My attempt complete with `watch` drama [is on SO](https://stackoverflow.com/questions/32557564/grunt-is-running-watch-task-and-waiting-forever-is-it-my-gruntfile-js-synt) if you're curious.

**Comment by m10n** [comment]
@T04435 @MichaelMallett 
[@maxbeatty](https://github.com/maxbeatty) hooked me up in [Slack](https://bootstrap-slack.herokuapp.com/) [#help](https://getbootstrap.slack.com/archives/help). The Gruntfile.js and package.json that finally worked for me are [here](https://github.com/maxbeatty/example-grunt-sass-bootstrap)
https://github.com/maxbeatty/example-grunt-sass-bootstrap
It's archived in case you encounter similar issues. Big up to [@tatygrassini](https://github.com/tatygrassini) as well. LMK if I can help.

**Comment by cvrebert** [comment]
@twbs/sass Thoughts on this? WontFix?

**Comment by cvrebert** [comment]
@twbs/sass Thoughts on this? WontFix?

**Comment by thomas-mcdonald** [comment]
Probably - my desire to add much to -sass is fairly limited now v4 is motoring forward, especially a new platform I have essentially nil experience with.
