### ISSUE TITLE
Include scss-lint configuration file

### ISSUE THREAD

**Issue by iampuma** [twbs/bootstrap-sass#985]
It would be great to have a scss-lint file included in the stylesheets assets folder.

As I mostly copy over the _variables.scss file and as consistency reason.

**Comment by cvrebert** [comment]
Since this is just an autogenerated translation of the upstream repo, I don't really see what the point would be.

**Comment by bingalls** [comment]
The point is to allow sass lint or style lint to cover bootstrap, as part of continuous integration.
Sass-lint now supports ignored files. Otherwise, here is partial gulp task to automatically clean bootstrap-variables.scss. See gulp-stylefmt Github site for details on its configuration.

const replace         = require('gulp-replace'),
    stylefmt        = require('gulp-stylefmt');

gulp.task('stylefmt', function () {
    return gulp.src('src/bootstrap-variables.scss')
        .pipe(replace('"', "'"))
        .pipe(replace(" 0", " "))
        .pipe(stylefmt())
        .pipe(gulp.dest('dest/'));
});
// for some reason, quotes & zeros did not automatically clean up.
